# Generated by Django 4.2.24 on 2025-09-27 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Краткий заголовок объявления', max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Подробное описание предмета обмена', max_length=400, verbose_name='Описание')),
                ('image_url', models.URLField(blank=True, help_text='Ссылка на изображение предмета', verbose_name='Изображение (URL)')),
                ('category', models.CharField(db_index=True, help_text='Категория товара или услуги', max_length=100, verbose_name='Категория')),
                ('condition', models.CharField(choices=[('new', 'новый'), ('used', 'б/у')], db_index=True, help_text='Состояние предмета (новый или б/у)', verbose_name='Состояние')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время публикации объявления', verbose_name='Дата создания')),
                ('user', models.ForeignKey(help_text='Владелец объявления', on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, help_text='Дополнительное сообщение к предложению', verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'ожидает'), ('accepted', 'принята'), ('rejected', 'отклонена')], db_index=True, default='pending', help_text='Текущий статус предложения', verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время отправки предложения', verbose_name='Дата создания')),
                ('ad_receiver', models.ForeignKey(help_text='Объявление, которому адресовано предложение', on_delete=django.db.models.deletion.CASCADE, related_name='received_proposals', to='ads.ad', verbose_name='Получатель')),
                ('ad_sender', models.ForeignKey(help_text='Объявление, с которого сделано предложение', on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to='ads.ad', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Предложение обмена',
                'verbose_name_plural': 'Предложения обмена',
            },
        ),
        migrations.AddConstraint(
            model_name='exchangeproposal',
            constraint=models.CheckConstraint(check=models.Q(('ad_sender', models.F('ad_receiver')), _negated=True), name='check_user'),
        ),
    ]
